#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 26 09:46:35 2018

@author: JieweiLu
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import tensorflow.contrib.slim as slim

from dataDecoder import tf_example_decoder_from_od


def read_TF_slim(file_tfRecord):
    queue = tf.train.string_input_producer([file_tfRecord])
    reader = tf.TFRecordReader()
    _,serialized_example = reader.read(queue)
    
    keys_to_features = {
      'image/encoded': tf.FixedLenFeature((), tf.string, default_value=''),
      'image/format': tf.FixedLenFeature((), tf.string, default_value='jpg'),
      'image/class/label': tf.FixedLenFeature(
          [], tf.int64, default_value=tf.zeros([], dtype=tf.int64))}

    items_to_handlers = {
      'image': slim.tfexample_decoder.Image(),
      'label': slim.tfexample_decoder.Tensor('image/class/label')}
   
    decoder = slim.tfexample_decoder.TFExampleDecoder(
        keys_to_features, items_to_handlers)


    tensor_dict = decoder.decode(serialized_example)
    
    return tensor_dict

def read_TF_od(file_tfRecord):
    '''
    Input: 
        The path of butterfly_train.record
        butterfly_train.record is generated by Wuming
    
    Output:
        return a dicrionary
    
    '''
        
    # define the decoder dictionary
    queue = tf.train.string_input_producer([file_tfRecord])
    reader = tf.TFRecordReader()
    decoder = tf_example_decoder_from_od.TfExampleDecoder()
    _,serialized_example = reader.read(queue)
    tensor_dict = decoder.decode(serialized_example)
    
    return tensor_dict
    